{% set name = "consolekit" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/consolekit-{{ version }}.tar.gz
  sha256: 55ea43e226863e1d618ec9b860c9842d84249d895c3376c03b158d8f3a335626

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.6
  run:
    - click >=7.1.2
    - colorama >=0.4.3
    - deprecation-alias >=0.1.1
    - domdf-python-tools >=2.6.0
    - mistletoe >=0.7.2
    - python >=3.6
    - typing-extensions !=3.10.0.1,>=3.10.0.0

test:
  imports:
    - consolekit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/domdfcoding/consolekit
  summary: Additional utilities for click.
  license: MIT
  license_file: LICENSE
  doc_url: https://consolekit.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - domdfcoding
