{% set name = "consolekit" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/domdfcoding/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7c9edbde4f1880fd4c08a7f6d8b1a26a4030ecdc0464a14b60e4930d0d2a8654

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<37]

requirements:
  host:
    - python
    - flit-core >=3.2,<4
    - pip
  run:
    - python
    - click >=7.1.2,<8.2
    - colorama >=0.4.3  # [py<310 and win]
    - deprecation-alias >=0.1.1
    - domdf-python-tools >=3.8.0
    - mistletoe >=0.7.2
    - typing-extensions >=3.10.0.0,!=3.10.0.1
  run_constrained:
    # terminals
    - psutil >=5.8.0

test:
  source_files:
    - tests
  imports:
    - consolekit
  requires:
    - pip
    - pytest >=6.0.0
    - coincidence >=0.1.0
    - pytest-regressions >=2.0.2
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv tests

about:
  home: https://github.com/domdfcoding/consolekit
  summary: Additional utilities for click.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Additional utilities for click.
  doc_url: https://consolekit.readthedocs.io
  dev_url: https://github.com/domdfcoding/consolekit

extra:
  recipe-maintainers:
    - domdfcoding
